name = "quotation-system"
main = "dist/worker.js"
compatibility_date = "2024-02-20"

[[d1_databases]]
binding = "DB"
database_name = "quotation-history"
database_id = "fe5975d3-4a87-4965-b86a-4670db3656e7"

[vars]
API_TOKEN = "Kqm0uVxJuVRkJ1GUoAwT4SrfvYAbaVbcwV6jQ8hY"
MAIN_SITE_URL = "https://luocompany.net"

# 修改路由配置
[[routes]]
pattern = "bj.luocompany.net/*"
zone_name = "luocompany.net"

[site]
bucket = "./public"

[triggers]
crons = []

[build]
command = "npm run build:worker"
watch_dir = "src"

[build.upload]
format = "modules"

[env.production]
workers_dev = false
vars = { MAIN_SITE_URL = "https://luocompany.net" }

[env.development]
workers_dev = true
vars = { MAIN_SITE_URL = "http://localhost:3000" }

# 增加超时和连接配置
[http_timeout]
read = 30000
write = 30000
connect = 30000

[http]
max_retries = 3
retry_on = [500, 502, 503, 504, 408, 429]
retry_delay = 1000