name = "mluonet-users"
main = "src/worker.ts"
compatibility_date = "2024-02-20"

[[d1_databases]]
binding = "USERS_DB"
database_name = "mluonet-users"
database_id = "f8dac0b4-d25a-4d11-b64f-b592ea24e17d"

[vars]
API_TOKEN = "Kqm0uVxJuVRkJ1GUoAwT4SrfvYAbaVbcwV6jQ8hY"
MAIN_SITE_URL = "https://luocompany.net"

# 启用自定义域名配置，绑定 udb.luocompany.net
# 注意：如果主站迁移到 Netlify，请确保 DNS 配置正确
[[routes]]
pattern = "udb.luocompany.net"
zone_name = "luocompany.net"
custom_domain = true

[site]
bucket = "./public"

[triggers]
crons = []

[env.production]
workers_dev = false
vars = { MAIN_SITE_URL = "https://luocompany.net" }

[env.development]
workers_dev = true
vars = { MAIN_SITE_URL = "http://localhost:3000" }