name = "mluonet-users"
main = "src/worker.ts"
compatibility_date = "2024-02-20"

[[d1_databases]]
binding = "USERS_DB"
database_name = "mluonet-users"
database_id = "f8dac0b4-d25a-4d11-b64f-b592ea24e17d"

[vars]
API_TOKEN = "Kqm0uVxJuVRkJ1GUoAwT4SrfvYAbaVbcwV6jQ8hY"
MAIN_SITE_URL = "https://luocompany.net"

# 启用自定义域名配置，绑定 udb.luocompany.net
[[routes]]
pattern = "udb.luocompany.net"
zone_name = "luocompany.net"
custom_domain = true

[site]
bucket = "./public"

[triggers]
crons = []

# 已删除[build]配置

[env.production]
workers_dev = false
vars = { MAIN_SITE_URL = "https://luocompany.net" }

[env.development]
workers_dev = true
vars = { MAIN_SITE_URL = "http://localhost:3000" }

# 增加超时和连接配置
[http_timeout]
read = 60000
write = 60000
connect = 30000

[http]
max_retries = 5
retry_on = [500, 502, 503, 504, 408, 429, "ERR_CONNECTION_CLOSED"]
retry_delay = 1000
max_concurrent_requests = 100

# 免费计划不支持CPU限制，已移除[limits]配置